type Query {
  user(id: ID!): User!
  tables(limit: Int, skip: Int): TableConnection!
}

type Mutation {
  login(args: LoginInput!): Token!
  register(args: RegisterInput!): String!
}

input LoginInput {
  email: String!
  password: String!
}

input RegisterInput {
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

type Token {
  accessToken: String!
  refreshToken: String
}

type User {
  fullName: String!
  email: String!
}

type Table {
  id: ID!
  title: String!
  limit: Int
  DeadLine: String
  Fields: [String!]!
  disabled: Boolean!
}

type TableConnection {
  node: [Table!]!
  hasMore: Boolean!
  cursor: ID!
}
